uvicorn:
  host: "0.0.0.0"
  port: 8000
  # reload: true
  log_config: "src/resources/log.ini"

fastapi:
  title: Python FastAPI Server
  version: 0.0.1
  contact:
    name: djccnt15
    url: https://djccnt15.github.io/
    email: djccnt15@gmail.com
  license_info:
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  description: FastAPI Server
  openapi_tags:
    - name: default
      externalDocs:
        description: External docs
        url: https://djccnt15.github.io/pages/tags/#fastapi
    - name: user
      description: User domain API, Such as **SignUp**, **LogIn**, etc.
  cors_orign:
    - http://localhost:5173
    - http://127.0.0.1:5173
  auth:
    token_expire_minutes: 1440
    secret_key: secret_key
    algorithm: algorithm

db:
  url:
    drivername: mysql+aiomysql
    username: qwer
    password: asdf
    host: localhost
    port: 3306
    database: test
  engine:
    pool_pre_ping: true
    pool_recycle: 3600
    echo: false

redis:
  host: 127.0.0.1
  port: 6379
  decode_responses: true
  db: 0